### ISSUE TITLE
saving/loading vectorizers

### ISSUE THREAD

**Issue by andersonbcdefg** [raphaelsty/LeNLP#1]
love this project! how would you recommend serializing and deserializing these objects once trained?

**Comment by raphaelsty** [comment]
Hi @andersonbcdefg, thank's for your feedback! All the object except FlashText are serializable using pickle

I'm not sure how to make flashtext serializable with rust

**Comment by andersonbcdefg** [comment]
that's great, i think that should mean they're compatible with joblib. i'll close this issue and re-open if i have any trouble saving/loading with pickle. :)
